{
 "title": "Kafka-Example-1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Process Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (processName) (sum_over_time( {job=\"kafka\"} | json | unwrap count [$__interval] ))",
     "legendFormat": "{{processName}}"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate( {job=\"kafka\"} | json [1h] ) * 3600 )",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (statusCode) (count_over_time( {job=\"kafka\"} | json [$__interval] ))",
     "legendFormat": "{{statusCode}}"
    }
   ]
  }
 ]
}